-- Supabase PostgreSQL Schema Migration Script
-- Run this in the Supabase SQL Editor

-- 1. Create `users` table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('patient', 'consultant', 'admin')),
    phone TEXT,
    dob TEXT,
    medical_history TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'pending')),
    assigned_difficulty TEXT,
    specialty TEXT,
    doctor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    otp TEXT,
    otp_expiry TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. Create `practice_results` table
CREATE TABLE IF NOT EXISTS practice_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    word TEXT NOT NULL,
    accuracy REAL NOT NULL,
    confidence REAL NOT NULL,
    errors INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. Create `reference_audios` table
CREATE TABLE IF NOT EXISTS reference_audios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename TEXT UNIQUE NOT NULL,
    display_name TEXT NOT NULL,
    difficulty TEXT NOT NULL CHECK (difficulty IN ('Basic', 'Medium', 'Hard')) DEFAULT 'Basic',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. Create `live_sessions` table
CREATE TABLE IF NOT EXISTS live_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    consultant_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    session_date TEXT NOT NULL,
    session_time TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'completed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Note: In Supabase you'll also want to make sure the Auth and Storage buckets are set up, 
-- but the migration script will auto-create the storage buckets.
